google.places.api-key=${GOOGLE_PLACES_API_KEY}
google.places.target-count=100

## H2 (for dev)
#spring.datasource.url=jdbc:h2:file:./data/beautysalondb;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

## H2 Console – http://localhost:8080/h2-console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#server.port=8080
#spring.application.name=BeautySalonApp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL (for prod)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:beautysalondb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false


# Logging
logging.level.com.warsaw.salons=INFO
logging.level.org.springframework.web=WARN

resilience4j.retry.instances.googlePlaces.max-attempts=2
resilience4j.retry.instances.googlePlaces.wait-duration=2s
resilience4j.retry.instances.googlePlaces.retry-exceptions=org.springframework.web.client.RestClientException

resilience4j.ratelimiter.instances.googlePlaces.limit-for-period=10
resilience4j.ratelimiter.instances.googlePlaces.limit-refresh-period=1s
resilience4j.ratelimiter.instances.googlePlaces.timeout-duration=5s

